-- ========================================
-- DISABLE RLS FOR DEBUGGING
-- WARNING: This removes all row-level security!
-- Only use this temporarily to diagnose issues
-- ========================================

-- Disable RLS on all tables
ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.properties DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.enquiries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.blog_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.testimonials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.newsletter_subscribers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contact_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.site_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.media_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.developers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_highlights DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_amenities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_specifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.nearby_places DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_rera_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.group_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.city_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.property_configurations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ai_api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ai_agent_configurations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.saved_properties DISABLE ROW LEVEL SECURITY;

SELECT 'RLS DISABLED on all tables - FOR DEBUGGING ONLY!' as warning;
